name: CI Robot Framework

on:
  push:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          run: docker run --shm-size=1g --user $(id -u):$(id -g) -e BROWSER=chrome -v $WORKSPACE/robot-tests:/opt/robotframework/tests:Z -v $WORKSPACE/robot-reports:/opt/robotframework/reports:Z ppodgorsek/robot-framework:latest
          env:
            #BROWSER: chrome
            ROBOT_TESTS_DIR: ./test/feature
            ROBOT_REPORTS_DIR: ./report
            
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: report
            path: ./report
            
        - name: Deploy report page to GitHub Page
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./report
