name: CI Robot Framework

on:
  push:
    branches: [ main ]

jobs:
    run_test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run tests
          run: |
            mkdir ${{github.workspace}}/reports
            docker run --shm-size=1g -e BROWSER=headlesschrome \
            -v ${{github.workspace}}/tests:/opt/robotframework/tests:Z \
            -v ${{github.workspace}}/reports:/opt/robotframework/reports:Z \
            --user 1001:1000 \
            ppodgorsek/robot-framework:latest
          
        - name: Upload tests results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ./reports
            
        - name: Deploy report page to GitHub Page
          uses: peaceiris/actions-gh-pages@v3
          if: always()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./reports
